// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgSolvePuzzle } from "./types/gchain/snow/tx";
import { MsgStartGame } from "./types/gchain/snow/tx";

import { Game as typeGame} from "./types"
import { Params as typeParams} from "./types"
import { SystemInfo as typeSystemInfo} from "./types"

export { MsgSolvePuzzle, MsgStartGame };

type sendMsgSolvePuzzleParams = {
  value: MsgSolvePuzzle,
  fee?: StdFee,
  memo?: string
};

type sendMsgStartGameParams = {
  value: MsgStartGame,
  fee?: StdFee,
  memo?: string
};


type msgSolvePuzzleParams = {
  value: MsgSolvePuzzle,
};

type msgStartGameParams = {
  value: MsgStartGame,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgSolvePuzzle({ value, fee, memo }: sendMsgSolvePuzzleParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSolvePuzzle: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSolvePuzzle({ value: MsgSolvePuzzle.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSolvePuzzle: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgStartGame({ value, fee, memo }: sendMsgStartGameParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgStartGame: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgStartGame({ value: MsgStartGame.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgStartGame: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgSolvePuzzle({ value }: msgSolvePuzzleParams): EncodeObject {
			try {
				return { typeUrl: "/gchain.snow.MsgSolvePuzzle", value: MsgSolvePuzzle.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSolvePuzzle: Could not create message: ' + e.message)
			}
		},
		
		msgStartGame({ value }: msgStartGameParams): EncodeObject {
			try {
				return { typeUrl: "/gchain.snow.MsgStartGame", value: MsgStartGame.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgStartGame: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						Game: getStructure(typeGame.fromPartial({})),
						Params: getStructure(typeParams.fromPartial({})),
						SystemInfo: getStructure(typeSystemInfo.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			GchainSnow: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;