// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gchain/player/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc1cf4ab9a03b201, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc1cf4ab9a03b201, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryReadPlayerStatusRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryReadPlayerStatusRequest) Reset()         { *m = QueryReadPlayerStatusRequest{} }
func (m *QueryReadPlayerStatusRequest) String() string { return proto.CompactTextString(m) }
func (*QueryReadPlayerStatusRequest) ProtoMessage()    {}
func (*QueryReadPlayerStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc1cf4ab9a03b201, []int{2}
}
func (m *QueryReadPlayerStatusRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReadPlayerStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReadPlayerStatusRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReadPlayerStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReadPlayerStatusRequest.Merge(m, src)
}
func (m *QueryReadPlayerStatusRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryReadPlayerStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReadPlayerStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReadPlayerStatusRequest proto.InternalMessageInfo

func (m *QueryReadPlayerStatusRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryReadPlayerStatusResponse struct {
	Lhc *Lhcdata `protobuf:"bytes,1,opt,name=lhc,proto3" json:"lhc,omitempty"`
}

func (m *QueryReadPlayerStatusResponse) Reset()         { *m = QueryReadPlayerStatusResponse{} }
func (m *QueryReadPlayerStatusResponse) String() string { return proto.CompactTextString(m) }
func (*QueryReadPlayerStatusResponse) ProtoMessage()    {}
func (*QueryReadPlayerStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc1cf4ab9a03b201, []int{3}
}
func (m *QueryReadPlayerStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReadPlayerStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReadPlayerStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReadPlayerStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReadPlayerStatusResponse.Merge(m, src)
}
func (m *QueryReadPlayerStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryReadPlayerStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReadPlayerStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReadPlayerStatusResponse proto.InternalMessageInfo

func (m *QueryReadPlayerStatusResponse) GetLhc() *Lhcdata {
	if m != nil {
		return m.Lhc
	}
	return nil
}

type QueryReadSnowStatusRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryReadSnowStatusRequest) Reset()         { *m = QueryReadSnowStatusRequest{} }
func (m *QueryReadSnowStatusRequest) String() string { return proto.CompactTextString(m) }
func (*QueryReadSnowStatusRequest) ProtoMessage()    {}
func (*QueryReadSnowStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc1cf4ab9a03b201, []int{4}
}
func (m *QueryReadSnowStatusRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReadSnowStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReadSnowStatusRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReadSnowStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReadSnowStatusRequest.Merge(m, src)
}
func (m *QueryReadSnowStatusRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryReadSnowStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReadSnowStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReadSnowStatusRequest proto.InternalMessageInfo

func (m *QueryReadSnowStatusRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryReadSnowStatusResponse struct {
	Snow *Snowdata `protobuf:"bytes,1,opt,name=snow,proto3" json:"snow,omitempty"`
}

func (m *QueryReadSnowStatusResponse) Reset()         { *m = QueryReadSnowStatusResponse{} }
func (m *QueryReadSnowStatusResponse) String() string { return proto.CompactTextString(m) }
func (*QueryReadSnowStatusResponse) ProtoMessage()    {}
func (*QueryReadSnowStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc1cf4ab9a03b201, []int{5}
}
func (m *QueryReadSnowStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReadSnowStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReadSnowStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReadSnowStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReadSnowStatusResponse.Merge(m, src)
}
func (m *QueryReadSnowStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryReadSnowStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReadSnowStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReadSnowStatusResponse proto.InternalMessageInfo

func (m *QueryReadSnowStatusResponse) GetSnow() *Snowdata {
	if m != nil {
		return m.Snow
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "gchain.player.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "gchain.player.QueryParamsResponse")
	proto.RegisterType((*QueryReadPlayerStatusRequest)(nil), "gchain.player.QueryReadPlayerStatusRequest")
	proto.RegisterType((*QueryReadPlayerStatusResponse)(nil), "gchain.player.QueryReadPlayerStatusResponse")
	proto.RegisterType((*QueryReadSnowStatusRequest)(nil), "gchain.player.QueryReadSnowStatusRequest")
	proto.RegisterType((*QueryReadSnowStatusResponse)(nil), "gchain.player.QueryReadSnowStatusResponse")
}

func init() { proto.RegisterFile("gchain/player/query.proto", fileDescriptor_bc1cf4ab9a03b201) }

var fileDescriptor_bc1cf4ab9a03b201 = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x31, 0x6f, 0xd3, 0x40,
	0x18, 0x86, 0x6d, 0x5a, 0x82, 0x38, 0x04, 0x42, 0x47, 0x43, 0x8b, 0xdb, 0x1a, 0xf0, 0xd4, 0xd6,
	0xe0, 0x53, 0x1a, 0x09, 0x31, 0x77, 0xa3, 0x62, 0x28, 0xce, 0xc6, 0x52, 0x7d, 0xb1, 0x4f, 0x8e,
	0x25, 0xf7, 0xce, 0xf5, 0x5d, 0x28, 0x11, 0x62, 0xe1, 0x17, 0x20, 0xb1, 0x31, 0xf2, 0x2f, 0xf8,
	0x07, 0x1d, 0x23, 0xb1, 0x30, 0x21, 0x94, 0xf0, 0x43, 0x90, 0xef, 0xce, 0x41, 0x76, 0x1c, 0x94,
	0xed, 0x92, 0xf7, 0xfd, 0xde, 0xef, 0xd1, 0xfb, 0x25, 0xe8, 0x51, 0x12, 0x8d, 0x20, 0x65, 0x24,
	0xcf, 0x60, 0x42, 0x0b, 0x72, 0x39, 0xa6, 0xc5, 0x24, 0xc8, 0x0b, 0x2e, 0x39, 0xbe, 0xab, 0xa5,
	0x40, 0x4b, 0xce, 0x56, 0xc2, 0x13, 0xae, 0x14, 0x52, 0xbe, 0xb4, 0xc9, 0xd9, 0x4b, 0x38, 0x4f,
	0x32, 0x4a, 0x20, 0x4f, 0x09, 0x30, 0xc6, 0x25, 0xc8, 0x94, 0x33, 0x61, 0xd4, 0xa3, 0x88, 0x8b,
	0x0b, 0x2e, 0xc8, 0x10, 0x04, 0xd5, 0xd9, 0xe4, 0x5d, 0x6f, 0x48, 0x25, 0xf4, 0x48, 0x0e, 0x49,
	0xca, 0x94, 0xd9, 0x78, 0x9d, 0x3a, 0x49, 0x0e, 0x05, 0x5c, 0x54, 0x39, 0xbb, 0x75, 0x2d, 0x1b,
	0x45, 0x31, 0x48, 0x58, 0x20, 0xd4, 0x44, 0xc1, 0xf8, 0xd5, 0x3f, 0xd5, 0xdb, 0x42, 0xf8, 0x4d,
	0xb9, 0xf8, 0x4c, 0xe5, 0x85, 0xf4, 0x72, 0x4c, 0x85, 0xf4, 0x4e, 0xd1, 0x83, 0xda, 0xb7, 0x22,
	0xe7, 0x4c, 0x50, 0xdc, 0x47, 0x1d, 0xbd, 0x77, 0xc7, 0x7e, 0x62, 0x1f, 0xdc, 0x39, 0xee, 0x06,
	0xb5, 0x0e, 0x02, 0x6d, 0x3f, 0xd9, 0xbc, 0xfe, 0xf5, 0xd8, 0x0a, 0x8d, 0xd5, 0x7b, 0x89, 0xf6,
	0x54, 0x56, 0x48, 0x21, 0x3e, 0x53, 0xbe, 0x81, 0x04, 0x39, 0xae, 0x76, 0xe1, 0x1d, 0x74, 0x0b,
	0xe2, 0xb8, 0xa0, 0x42, 0xa7, 0xde, 0x0e, 0xab, 0x8f, 0xde, 0x2b, 0xb4, 0xbf, 0x62, 0xd2, 0xf0,
	0x1c, 0xa0, 0x8d, 0x6c, 0x14, 0x19, 0x98, 0x87, 0x0d, 0x98, 0xd7, 0xba, 0x85, 0xb0, 0xb4, 0x78,
	0x2f, 0x90, 0xb3, 0x88, 0x1a, 0x30, 0x7e, 0xb5, 0x2e, 0xc2, 0x29, 0xda, 0x6d, 0x9d, 0x33, 0x00,
	0x3e, 0xda, 0x2c, 0xfb, 0x34, 0x04, 0xdb, 0x0d, 0x82, 0x81, 0xa9, 0x3a, 0x54, 0xa6, 0xe3, 0xef,
	0x1b, 0xe8, 0xa6, 0x0a, 0xc3, 0x0c, 0x75, 0x74, 0x55, 0xf8, 0x69, 0x63, 0x64, 0xf9, 0x16, 0x8e,
	0xf7, 0x3f, 0x8b, 0xe6, 0xf0, 0xf6, 0x3f, 0xfd, 0xf8, 0xf3, 0xe5, 0xc6, 0x36, 0xee, 0x92, 0xb6,
	0x5f, 0x09, 0xfe, 0x66, 0xa3, 0xfb, 0xcd, 0x12, 0xb1, 0xdf, 0x96, 0xbb, 0xe2, 0x48, 0xce, 0xb3,
	0xf5, 0xcc, 0x06, 0xa7, 0xaf, 0x70, 0x9e, 0x63, 0xbf, 0x81, 0x53, 0x50, 0x88, 0xcf, 0xf5, 0xfb,
	0x5c, 0xa8, 0x11, 0xf2, 0xc1, 0x34, 0xfd, 0x11, 0x7f, 0xb5, 0xd1, 0xbd, 0x7a, 0xcd, 0xf8, 0x70,
	0xd5, 0xd6, 0xa5, 0x13, 0x3a, 0x47, 0xeb, 0x58, 0x0d, 0x5e, 0x4f, 0xe1, 0xf9, 0xf8, 0xb0, 0x0d,
	0xaf, 0x3c, 0xd5, 0x12, 0xdc, 0x09, 0xb9, 0x9e, 0xb9, 0xf6, 0x74, 0xe6, 0xda, 0xbf, 0x67, 0xae,
	0xfd, 0x79, 0xee, 0x5a, 0xd3, 0xb9, 0x6b, 0xfd, 0x9c, 0xbb, 0xd6, 0xdb, 0xae, 0xc9, 0x78, 0x5f,
	0xa5, 0xc8, 0x49, 0x4e, 0xc5, 0xb0, 0xa3, 0xfe, 0x5e, 0xfd, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x57, 0xb6, 0x3c, 0x77, 0x41, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of ReadPlayerStatus items.
	ReadPlayerStatus(ctx context.Context, in *QueryReadPlayerStatusRequest, opts ...grpc.CallOption) (*QueryReadPlayerStatusResponse, error)
	// Queries a list of ReadSnowStatus items.
	ReadSnowStatus(ctx context.Context, in *QueryReadSnowStatusRequest, opts ...grpc.CallOption) (*QueryReadSnowStatusResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/gchain.player.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ReadPlayerStatus(ctx context.Context, in *QueryReadPlayerStatusRequest, opts ...grpc.CallOption) (*QueryReadPlayerStatusResponse, error) {
	out := new(QueryReadPlayerStatusResponse)
	err := c.cc.Invoke(ctx, "/gchain.player.Query/ReadPlayerStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ReadSnowStatus(ctx context.Context, in *QueryReadSnowStatusRequest, opts ...grpc.CallOption) (*QueryReadSnowStatusResponse, error) {
	out := new(QueryReadSnowStatusResponse)
	err := c.cc.Invoke(ctx, "/gchain.player.Query/ReadSnowStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of ReadPlayerStatus items.
	ReadPlayerStatus(context.Context, *QueryReadPlayerStatusRequest) (*QueryReadPlayerStatusResponse, error)
	// Queries a list of ReadSnowStatus items.
	ReadSnowStatus(context.Context, *QueryReadSnowStatusRequest) (*QueryReadSnowStatusResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ReadPlayerStatus(ctx context.Context, req *QueryReadPlayerStatusRequest) (*QueryReadPlayerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadPlayerStatus not implemented")
}
func (*UnimplementedQueryServer) ReadSnowStatus(ctx context.Context, req *QueryReadSnowStatusRequest) (*QueryReadSnowStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadSnowStatus not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gchain.player.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ReadPlayerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReadPlayerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ReadPlayerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gchain.player.Query/ReadPlayerStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ReadPlayerStatus(ctx, req.(*QueryReadPlayerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ReadSnowStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReadSnowStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ReadSnowStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gchain.player.Query/ReadSnowStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ReadSnowStatus(ctx, req.(*QueryReadSnowStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gchain.player.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ReadPlayerStatus",
			Handler:    _Query_ReadPlayerStatus_Handler,
		},
		{
			MethodName: "ReadSnowStatus",
			Handler:    _Query_ReadSnowStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gchain/player/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryReadPlayerStatusRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReadPlayerStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReadPlayerStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryReadPlayerStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReadPlayerStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReadPlayerStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Lhc != nil {
		{
			size, err := m.Lhc.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryReadSnowStatusRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReadSnowStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReadSnowStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryReadSnowStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReadSnowStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReadSnowStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Snow != nil {
		{
			size, err := m.Snow.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryReadPlayerStatusRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryReadPlayerStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Lhc != nil {
		l = m.Lhc.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryReadSnowStatusRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryReadSnowStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Snow != nil {
		l = m.Snow.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReadPlayerStatusRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReadPlayerStatusRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReadPlayerStatusRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReadPlayerStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReadPlayerStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReadPlayerStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lhc", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Lhc == nil {
				m.Lhc = &Lhcdata{}
			}
			if err := m.Lhc.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReadSnowStatusRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReadSnowStatusRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReadSnowStatusRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReadSnowStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReadSnowStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReadSnowStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Snow", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Snow == nil {
				m.Snow = &Snowdata{}
			}
			if err := m.Snow.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
